<?php

return [
    /*
     * Design Philosophy LP の本文データです。
     * 追加、除外、並び替えは enabled と sort_order で制御し、
     * React 側には固定配列を持たせません。
     *
     * 本番で config:cache を使っている環境では、このファイルを変更した後に
     * config cache を再生成する必要があります。DB・S3・画像URLは今回扱いません。
     */
    'sections' => [
        [
            'key' => 'overview',
            'sort_order' => 10,
            'enabled' => true,
            'eyebrow' => 'Design Philosophy',
            'visual_type' => 'hero',
            'icon' => 'Compass',
            'title' => '設計思想',
            'lead' => 'なぜこの構成にしているか。',
            'body' => '責務、段階、確認手段を分け、AI支援でも人間が判断しながら壊れにくく育てるための考え方です。',
            'proof_label' => 'このページで扱うこと',
            'proof_text' => '作る、分ける、確認する、読み直す。その判断基準を1テーマずつ追えるようにします。',
            'items' => [
                ['label' => '作る', 'description' => '目的を決める'],
                ['label' => '分ける', 'description' => '責務を置く'],
                ['label' => '確認する', 'description' => 'ズレを検出する'],
                ['label' => '読み直す', 'description' => '意図を回収する'],
            ],
        ],
        [
            'key' => 'responsibility-boundaries',
            'sort_order' => 20,
            'enabled' => true,
            'eyebrow' => 'Responsibility',
            'visual_type' => 'flow',
            'icon' => 'Workflow',
            'title' => '責務を分ける',
            'lead' => '変更箇所と原因調査の範囲を狭める。',
            'body' => 'HTTP入口、ユースケース手順、業務判断、データ境界、出力整形、画面表示を分けて見ます。',
            'proof_label' => '判断基準',
            'proof_text' => 'どの理由で変わったのかを、入力、手順、判断、取得、整形、表示に分けて確認します。',
            'items' => [
                ['label' => 'Controller / Request', 'description' => '入口と入力形式'],
                ['label' => 'Action', 'description' => 'ユースケース手順'],
                ['label' => 'Service / Repository / DTO', 'description' => '判断とデータ境界'],
                ['label' => 'Responder', 'description' => '出力整形'],
                ['label' => 'React / Inertia', 'description' => '画面表示'],
            ],
        ],
        [
            'key' => 'staged-development',
            'sort_order' => 30,
            'enabled' => true,
            'eyebrow' => 'Stages',
            'visual_type' => 'steps',
            'icon' => 'Milestone',
            'title' => '段階を分ける',
            'lead' => '構想、UI確認、接続検証、本実装を混ぜない。',
            'body' => '速く作った固定データや仮処理を、そのまま完成扱いにしないために段階を分けます。',
            'proof_label' => '進め方',
            'proof_text' => '各段階で確認したことを、次の段階の仕様、UI契約、責務境界、テスト観点へ変換します。',
            'items' => [
                ['label' => 'IDEA BOARD', 'description' => '目的と未確定事項を整理する'],
                ['label' => 'MOCK', 'description' => '固定データでUIを確認する'],
                ['label' => 'PROTOTYPE', 'description' => '導線と接続を検証する'],
                ['label' => 'PRODUCT', 'description' => '仕様と責務とテストを固定する'],
            ],
        ],
        [
            'key' => 'feedback-controls',
            'sort_order' => 40,
            'enabled' => true,
            'eyebrow' => 'Feedback Controls',
            'visual_type' => 'loop',
            'icon' => 'Radar',
            'title' => 'ズレを検出する',
            'lead' => '設計を言いっぱなしにしない。',
            'body' => 'docs、test、PR、Sensorsを、変更後に戻れるかを確認するための手段として扱います。',
            'proof_label' => '確認手段',
            'proof_text' => 'Sensorsは詳細を画面へ複製せず、漏れや危険変更を検出する台帳として参照します。',
            'items' => [
                ['label' => '実装 / docs変更', 'description' => '差分を作る'],
                ['label' => 'test / build / PR', 'description' => '仕様と差分を確認する'],
                ['label' => 'Sensors', 'description' => '漏れや危険変更を拾う'],
                ['label' => '修正 / 再確認', 'description' => 'ズレを戻す'],
            ],
        ],
        [
            'key' => 'human-led-ai',
            'sort_order' => 50,
            'enabled' => true,
            'eyebrow' => 'Human Led AI',
            'visual_type' => 'split',
            'icon' => 'Bot',
            'title' => 'AIと人間の分担',
            'lead' => 'AIは補助、人間は判断を持つ。',
            'body' => 'AIに丸投げするのではなく、構造と判断を人間側に残し、差分をレビューできる形にします。',
            'proof_label' => '分担',
            'proof_text' => '速く作ることと、後から保守できる形に留めることを分けて扱います。',
            'left_label' => '人間',
            'right_label' => 'AI',
            'left_items' => ['仕様', '責務境界', '完成判定', 'merge判断'],
            'right_items' => ['調査', '実装補助', '差分修正', 'レビュー補助'],
        ],
        [
            'key' => 'understanding-reboot',
            'sort_order' => 60,
            'enabled' => true,
            'eyebrow' => 'Understanding Reboot',
            'visual_type' => 'sources',
            'icon' => 'BookOpen',
            'title' => '理解を再起動する',
            'lead' => '後から読んでも、意図と注意を回収できる状態にする。',
            'body' => '会話や一時メモだけに依存せず、目的、責務、入力、出力、禁止事項を読み直せる場所へ残します。',
            'proof_label' => '読み直せる状態',
            'proof_text' => '次の作業者が、現在地と変更時の注意をコードとdocsから回収できるようにします。',
            'items' => [
                ['label' => 'docs', 'description' => '目的と責務'],
                ['label' => '型 / DTO', 'description' => '入力と出力'],
                ['label' => 'コメント', 'description' => '意図と制約'],
                ['label' => 'test', 'description' => '実行可能な仕様'],
            ],
        ],
        [
            'key' => 'closing',
            'sort_order' => 70,
            'enabled' => true,
            'eyebrow' => 'Keep It Traceable',
            'visual_type' => 'closing',
            'icon' => 'RefreshCcw',
            'title' => '作る。分ける。確認する。読み直す。',
            'lead' => 'この順番を残すためのポートフォリオです。',
            'body' => '派手に見せることより、なぜそうしたかを後から追えることを優先します。',
            'proof_label' => '締め方',
            'proof_text' => '構成の理由、判断した場所、確認した結果を分けて残します。',
            'items' => [
                ['label' => '作る', 'description' => '目的を固定する'],
                ['label' => '分ける', 'description' => '責務を置く'],
                ['label' => '確認する', 'description' => 'ズレを戻す'],
                ['label' => '読み直す', 'description' => '次へつなぐ'],
            ],
        ],
    ],
];
